services:
  web:
    build: ./app
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      SMTP_USER: user
      SMTP_PASS: user
    volumes:
      - ./:/var/www/html
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: camagru
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge