services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./srcs:/var/www/srcs:ro
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf
    command: ["apache2-foreground"]